"""initial schema

Revision ID: 17d4a99b0301
Revises: 
Create Date: 2026-01-07 00:04:30.390690

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d4a99b0301'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('annual_revenue', sa.Float(), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('current_challenges', sa.Text(), nullable=True),
    sa.Column('industry_focus', sa.String(length=100), nullable=True),
    sa.Column('estimated_annual_savings', sa.Float(), nullable=True),
    sa.Column('roi_percentage', sa.Float(), nullable=True),
    sa.Column('payback_period_months', sa.Float(), nullable=True),
    sa.Column('demo_scheduled', sa.Boolean(), nullable=False),
    sa.Column('demo_date', sa.DateTime(), nullable=True),
    sa.Column('demo_completed', sa.Boolean(), nullable=False),
    sa.Column('welcome_email_sent', sa.Boolean(), nullable=False),
    sa.Column('roi_report_sent', sa.Boolean(), nullable=False),
    sa.Column('last_email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('conversion_status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_contractor_email')
    )
    op.create_index('idx_contractor_company_name', 'contractor', ['company_name'], unique=False)
    op.create_index('idx_contractor_company_size', 'contractor', ['company_size'], unique=False)
    op.create_index('idx_contractor_conversion_status', 'contractor', ['conversion_status'], unique=False)
    op.create_index('idx_contractor_created_at', 'contractor', ['created_at'], unique=False)
    op.create_index('idx_contractor_demo_scheduled', 'contractor', ['demo_scheduled'], unique=False)
    op.create_index('idx_contractor_email', 'contractor', ['email'], unique=False)
    op.create_index(op.f('ix_contractor_company_name'), 'contractor', ['company_name'], unique=False)
    op.create_index(op.f('ix_contractor_company_size'), 'contractor', ['company_size'], unique=False)
    op.create_index(op.f('ix_contractor_conversion_status'), 'contractor', ['conversion_status'], unique=False)
    op.create_index(op.f('ix_contractor_created_at'), 'contractor', ['created_at'], unique=False)
    op.create_index(op.f('ix_contractor_demo_scheduled'), 'contractor', ['demo_scheduled'], unique=False)
    op.create_index(op.f('ix_contractor_email'), 'contractor', ['email'], unique=True)
    op.create_index(op.f('ix_contractor_id'), 'contractor', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_company_name', 'users', ['company_name'], unique=False)
    op.create_index('ix_user_created_at', 'users', ['created_at'], unique=False)
    op.create_index('ix_user_email', 'users', ['email'], unique=True)
    op.create_index('ix_user_email_verified', 'users', ['email_verified'], unique=False)
    op.create_index('ix_user_is_active', 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_company_name'), 'users', ['company_name'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_email_verified'), 'users', ['email_verified'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_table('contact_form_submission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('annual_revenue', sa.Float(), nullable=True),
    sa.Column('current_challenges', sa.Text(), nullable=True),
    sa.Column('interested_features', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submission_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contact_submission_contractor_id', 'contact_form_submission', ['contractor_id'], unique=False)
    op.create_index('idx_contact_submission_email', 'contact_form_submission', ['email'], unique=False)
    op.create_index('idx_contact_submission_status', 'contact_form_submission', ['status'], unique=False)
    op.create_index('idx_contact_submission_submission_date', 'contact_form_submission', ['submission_date'], unique=False)
    op.create_index(op.f('ix_contact_form_submission_contractor_id'), 'contact_form_submission', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_contact_form_submission_email'), 'contact_form_submission', ['email'], unique=False)
    op.create_index(op.f('ix_contact_form_submission_id'), 'contact_form_submission', ['id'], unique=False)
    op.create_index(op.f('ix_contact_form_submission_status'), 'contact_form_submission', ['status'], unique=False)
    op.create_index(op.f('ix_contact_form_submission_submission_date'), 'contact_form_submission', ['submission_date'], unique=False)
    op.create_table('demo_booking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('demo_date', sa.DateTime(), nullable=False),
    sa.Column('demo_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('attendee_name', sa.String(length=255), nullable=False),
    sa.Column('attendee_email', sa.String(length=255), nullable=False),
    sa.Column('attendee_phone', sa.String(length=20), nullable=True),
    sa.Column('meeting_type', sa.String(length=50), nullable=False),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('meeting_password', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('demo_completed', sa.Boolean(), nullable=False),
    sa.Column('demo_feedback', sa.Text(), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), nullable=False),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_demo_booking_contractor_id', 'demo_booking', ['contractor_id'], unique=False)
    op.create_index('idx_demo_booking_demo_date', 'demo_booking', ['demo_date'], unique=False)
    op.create_index('idx_demo_booking_status', 'demo_booking', ['status'], unique=False)
    op.create_index(op.f('ix_demo_booking_contractor_id'), 'demo_booking', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_demo_booking_created_at'), 'demo_booking', ['created_at'], unique=False)
    op.create_index(op.f('ix_demo_booking_demo_date'), 'demo_booking', ['demo_date'], unique=False)
    op.create_index(op.f('ix_demo_booking_id'), 'demo_booking', ['id'], unique=False)
    op.create_index(op.f('ix_demo_booking_status'), 'demo_booking', ['status'], unique=False)
    op.create_table('roi_calculation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('avg_project_value', sa.Float(), nullable=False),
    sa.Column('avg_delay_percentage', sa.Float(), nullable=False),
    sa.Column('num_projects_per_year', sa.Integer(), nullable=False),
    sa.Column('avg_project_duration_days', sa.Integer(), nullable=True),
    sa.Column('cost_per_day_delay', sa.Float(), nullable=False),
    sa.Column('ai_solution_annual_cost', sa.Float(), nullable=False),
    sa.Column('delay_reduction_percentage', sa.Float(), nullable=False),
    sa.Column('days_delayed_per_project', sa.Float(), nullable=True),
    sa.Column('annual_delay_cost', sa.Float(), nullable=True),
    sa.Column('estimated_savings_with_ai', sa.Float(), nullable=True),
    sa.Column('payback_period_months', sa.Float(), nullable=True),
    sa.Column('roi_percentage', sa.Float(), nullable=True),
    sa.Column('monthly_savings', sa.Float(), nullable=True),
    sa.Column('break_even_months', sa.Float(), nullable=True),
    sa.Column('three_year_savings', sa.Float(), nullable=True),
    sa.Column('five_year_savings', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('calculation_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_roi_calculation_calculation_date', 'roi_calculation', ['calculation_date'], unique=False)
    op.create_index('idx_roi_calculation_contractor_id', 'roi_calculation', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_roi_calculation_calculation_date'), 'roi_calculation', ['calculation_date'], unique=False)
    op.create_index(op.f('ix_roi_calculation_contractor_id'), 'roi_calculation', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_roi_calculation_id'), 'roi_calculation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roi_calculation_id'), table_name='roi_calculation')
    op.drop_index(op.f('ix_roi_calculation_contractor_id'), table_name='roi_calculation')
    op.drop_index(op.f('ix_roi_calculation_calculation_date'), table_name='roi_calculation')
    op.drop_index('idx_roi_calculation_contractor_id', table_name='roi_calculation')
    op.drop_index('idx_roi_calculation_calculation_date', table_name='roi_calculation')
    op.drop_table('roi_calculation')
    op.drop_index(op.f('ix_demo_booking_status'), table_name='demo_booking')
    op.drop_index(op.f('ix_demo_booking_id'), table_name='demo_booking')
    op.drop_index(op.f('ix_demo_booking_demo_date'), table_name='demo_booking')
    op.drop_index(op.f('ix_demo_booking_created_at'), table_name='demo_booking')
    op.drop_index(op.f('ix_demo_booking_contractor_id'), table_name='demo_booking')
    op.drop_index('idx_demo_booking_status', table_name='demo_booking')
    op.drop_index('idx_demo_booking_demo_date', table_name='demo_booking')
    op.drop_index('idx_demo_booking_contractor_id', table_name='demo_booking')
    op.drop_table('demo_booking')
    op.drop_index(op.f('ix_contact_form_submission_submission_date'), table_name='contact_form_submission')
    op.drop_index(op.f('ix_contact_form_submission_status'), table_name='contact_form_submission')
    op.drop_index(op.f('ix_contact_form_submission_id'), table_name='contact_form_submission')
    op.drop_index(op.f('ix_contact_form_submission_email'), table_name='contact_form_submission')
    op.drop_index(op.f('ix_contact_form_submission_contractor_id'), table_name='contact_form_submission')
    op.drop_index('idx_contact_submission_submission_date', table_name='contact_form_submission')
    op.drop_index('idx_contact_submission_status', table_name='contact_form_submission')
    op.drop_index('idx_contact_submission_email', table_name='contact_form_submission')
    op.drop_index('idx_contact_submission_contractor_id', table_name='contact_form_submission')
    op.drop_table('contact_form_submission')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email_verified'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_company_name'), table_name='users')
    op.drop_index('ix_user_is_active', table_name='users')
    op.drop_index('ix_user_email_verified', table_name='users')
    op.drop_index('ix_user_email', table_name='users')
    op.drop_index('ix_user_created_at', table_name='users')
    op.drop_index('ix_user_company_name', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_contractor_id'), table_name='contractor')
    op.drop_index(op.f('ix_contractor_email'), table_name='contractor')
    op.drop_index(op.f('ix_contractor_demo_scheduled'), table_name='contractor')
    op.drop_index(op.f('ix_contractor_created_at'), table_name='contractor')
    op.drop_index(op.f('ix_contractor_conversion_status'), table_name='contractor')
    op.drop_index(op.f('ix_contractor_company_size'), table_name='contractor')
    op.drop_index(op.f('ix_contractor_company_name'), table_name='contractor')
    op.drop_index('idx_contractor_email', table_name='contractor')
    op.drop_index('idx_contractor_demo_scheduled', table_name='contractor')
    op.drop_index('idx_contractor_created_at', table_name='contractor')
    op.drop_index('idx_contractor_conversion_status', table_name='contractor')
    op.drop_index('idx_contractor_company_size', table_name='contractor')
    op.drop_index('idx_contractor_company_name', table_name='contractor')
    op.drop_table('contractor')
    # ### end Alembic commands ###
